### ISSUE TITLE
`MemoryError` in `generate_html_report`

### ISSUE THREAD

**Issue by YenForYang** [AmgdGocha/DriveFS-Sleuth#21]
So I am testing on a pretty large `metadata_sqlite_db`, (slightly under 8 GiB). I managed to get the script to work all the way until the end (after several hours of waiting) (though it did use several GB of memory). Huge memory consumption when using `--html` as opposed to `--csv` overall, but I didn't actually get the `MemoryError` until `generate_html_report` was called.
```
[+] Processing C:\Users\Richard\AppData\Local\Google\DriveFS...
[+] Generating an HTML report: out\html_report.html...
Traceback (most recent call last):
  File "S:\DriveFS-Sleuth\drivefs_sleuth.py", line 272, in <module>
    generate_html_report(setup, html_output_path, search_results)
  File "S:\DriveFS-Sleuth\drivefs_sleuth\tasks.py", line 136, in generate_html_report
    report_file.write(template.render(setup=setup,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Richard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\Richard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "S:\DriveFS-Sleuth\drivefs_sleuth\html_resources\report_template.html", line 571, in top-level template code
    {{ generate_items_details_table(headers) }}
^^^^^^^^^
  File "C:\Users\Richard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\jinja2\runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "S:\DriveFS-Sleuth\drivefs_sleuth\html_resources\report_template.html", line 563, in template
    <td>{{ detail.properties[prop] }}</td>

MemoryError
```

Based on an old jinja issue mentioned [here](https://github.com/pallets/jinja/issues/372) it looks like there might be workarounds.

**Comment by AmgdGocha** [comment]
Hi @YenForYang,

Thanks for sharing this, I never got the change to perform this intense test before. If it's ok to share the DriveFS collection you're testing on so I can test please let me know, I'll share a drive link with you, otherwise, I'll have to check the issue your referenced and try to *blindly* implement it, and I'd ask you to kindly test it again since I don't have such a big collection .

Also would you mind telling which version of python you're using?

**Comment by YenForYang** [comment]
Unfortunately I can't share the DriveFS collection, but I will note that the CSV export worked and ended up being 1.56 GiB.  The python version used is 3.11.9. I think it's reasonable to assume that it's something specific to the HTML generation process, likely related to jinja. If I get a chance I'll retest the HTML version, but it is a huge memory hog (the HTML export even more so) so I can't ATM.

**Comment by AmgdGocha** [comment]
@YenForYang, I've utilized the Jinja streaming functionality to stream the output rather than rendering the entire template in memory, I believe this might help. I added a couple of statements to assess time and memory consumption. The consumption is reduced indeed but the difference is not so big since I'm testing with a small size collections. I'd appreciate it if you can give it a shot with the big data set you have. You can find the update in #24 (branch bugfix/fixing_memory_error_in_generate_html_report). The test requires installing `memory-profiler` package and the test results will be printed in the stdout.
![image](https://github.com/user-attachments/assets/cbbf073d-d58f-4a96-85f0-491c613d651d)

If the test went successful, please share a screenshot of the stdout.

**Comment by AmgdGocha** [comment]
@YenForYang, I've added new enhancements for the CSV as well. I also added a comment with the profiling results for both the HTML and the CSV generation. If you got time, please try it on the big database you have and let me know if these updates fixes your issue. 

Updates can be found here #24 (branch bugfix/fixing_memory_error_in_generate_html_report).

**Comment by YenForYang** [comment]
Didn't get to check up on this for a while, sorry for the late response. I will test it soon hopefully. Thanks for the fix!
